server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:

  datasource:
    url: jdbc:mysql://localhost/wanted?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create